create extension if not exists pgcrypto;

create table if not exists public.network_blocks (
  block_number bigint
    generated by default as identity
    primary key,

  block_hash text
    not null
    unique,

  previous_hash text
    not null,

  validator text
    not null
    default 'PLATON Ledger Engine',

  transaction_count integer
    not null
    default 1
    check (transaction_count > 0),

  confirmed_at timestamptz
    not null
    default now(),

  created_at timestamptz
    not null
    default now()
);

alter table public.network_blocks
enable row level security;

revoke all
on table public.network_blocks
from anon, authenticated;

alter table public.transactions
add column if not exists block_number bigint;

create index if not exists
  network_blocks_confirmed_at_idx
on public.network_blocks (
  confirmed_at desc
);

create index if not exists
  transactions_block_number_idx
on public.transactions (
  block_number
);

create or replace function public.assign_platon_block()
returns trigger
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_block_number bigint;
  v_previous_hash text;
  v_block_hash text;
  v_confirmed_at timestamptz;
begin
  perform pg_advisory_xact_lock(
    742903210071
  );

  v_confirmed_at :=
    coalesce(
      new.created_at,
      now()
    );

  select block_hash
  into v_previous_hash
  from public.network_blocks
  order by block_number desc
  limit 1;

  v_previous_hash :=
    coalesce(
      v_previous_hash,
      repeat('0', 64)
    );

  select nextval(
    pg_get_serial_sequence(
      'public.network_blocks',
      'block_number'
    )
  )
  into v_block_number;

  v_block_hash :=
    encode(
      extensions.digest(
        concat_ws(
          '|',
          'PLATON',
          v_block_number::text,
          v_previous_hash,
          new.id::text,
          coalesce(
            new.sender_wallet,
            'PLATON_NETWORK'
          ),
          new.receiver_wallet,
          new.amount::text,
          new.type,
          new.status,
          v_confirmed_at::text
        ),
        'sha256'
      ),
      'hex'
    );

  insert into public.network_blocks (
    block_number,
    block_hash,
    previous_hash,
    validator,
    transaction_count,
    confirmed_at,
    created_at
  )
  values (
    v_block_number,
    v_block_hash,
    v_previous_hash,
    'PLATON Ledger Engine',
    1,
    v_confirmed_at,
    v_confirmed_at
  );

  new.block_number :=
    v_block_number;

  return new;
end;
$$;

revoke all
on function public.assign_platon_block()
from public;

drop trigger if exists
  assign_platon_block_before_insert
on public.transactions;

create trigger
  assign_platon_block_before_insert
before insert
on public.transactions
for each row
execute function
  public.assign_platon_block();

do $$
declare
  transaction_row record;
  v_block_number bigint;
  v_previous_hash text;
  v_block_hash text;
  v_confirmed_at timestamptz;
begin
  perform pg_advisory_xact_lock(
    742903210071
  );

  for transaction_row in
    select
      id,
      sender_wallet,
      receiver_wallet,
      amount,
      type,
      status,
      created_at
    from public.transactions
    where block_number is null
    order by
      created_at asc nulls first,
      id asc
  loop
    v_confirmed_at :=
      coalesce(
        transaction_row.created_at,
        now()
      );

    select block_hash
    into v_previous_hash
    from public.network_blocks
    order by block_number desc
    limit 1;

    v_previous_hash :=
      coalesce(
        v_previous_hash,
        repeat('0', 64)
      );

    select nextval(
      pg_get_serial_sequence(
        'public.network_blocks',
        'block_number'
      )
    )
    into v_block_number;

    v_block_hash :=
      encode(
        extensions.digest(
          concat_ws(
            '|',
            'PLATON',
            v_block_number::text,
            v_previous_hash,
            transaction_row.id::text,
            coalesce(
              transaction_row.sender_wallet,
              'PLATON_NETWORK'
            ),
            transaction_row.receiver_wallet,
            transaction_row.amount::text,
            transaction_row.type,
            transaction_row.status,
            v_confirmed_at::text
          ),
          'sha256'
        ),
        'hex'
      );

    insert into public.network_blocks (
      block_number,
      block_hash,
      previous_hash,
      validator,
      transaction_count,
      confirmed_at,
      created_at
    )
    values (
      v_block_number,
      v_block_hash,
      v_previous_hash,
      'PLATON Ledger Engine',
      1,
      v_confirmed_at,
      v_confirmed_at
    );

    update public.transactions
    set block_number =
      v_block_number
    where id =
      transaction_row.id;
  end loop;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname =
      'transactions_block_number_fkey'
      and conrelid =
        'public.transactions'::regclass
  ) then
    alter table public.transactions
    add constraint
      transactions_block_number_fkey
    foreign key (
      block_number
    )
    references public.network_blocks (
      block_number
    );
  end if;
end;
$$;

alter table public.transactions
alter column block_number
set not null;
